<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$product = $this->getProduct();
$images = json_decode($block->getGalleryImagesJson(),true);
?>

<div class="gallery-placeholder _block-content-loading slick-slider" data-gallery-role="gallery-placeholder">
    <?php foreach ($images as $i => $image): ?>
        <div class="item">
            <?php $altText = $image['caption'] ? $image['caption'] : $product->getName(); ?>
            <img src="<?php echo $image['img']?>" alt="<?php echo $altText ?>">
        </div>
    <?php endforeach ?>
</div>

